apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: deck1
        image: docker-prod-local.si1ocevar01.clustere.ifdsgroup.ca/ifast/deck:latest
        command: ["/bin/sh", "-c"]
        args:
        - >
          cd /root
          [ ! -d deck ] && git clone -- branch dev https://github.com/dkazhdan1/deck.git && deck dump -o - >/root/deck/kong.yaml && cd deck\
           && git add kong.yaml && tag=`date +"%H-%M-%S-%H:%M"`&& git config --global user.name ifds && git config --global user.email ifds@a.com && git commit -m $tag || true\
           &&  git push https://dkazhdan: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@github.com/dkazhdan1/deck.git --all  && sleep infinity
          #deck dump -o - >/root/deck/kong.yaml
          #cd deck
          #git add kong.yaml
          #tag=`date +"%H-%M-%S-%H:%M"`
          #git commit -m $tag
          #git push
          sleep infinity
